services:
  - type: web
    name: soundswap-frontend
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_URL
        value: https://your-backend.vercel.app
      - key: VITE_FIREBASE_CONFIG
        value: '{
          "apiKey": "AIzaSyB4d9DUu0B7NG3mb-jRApMqE32siJESZUg",
          "authDomain": "soundswap-7e780.firebaseapp.com",
          "projectId": "soundswap-7e780",
          "storageBucket": "soundswap-7e780.firebasestorage.app",
          "messagingSenderId": "1022111514649",
          "appId": "Y1:1022111514649:web:3f4eae618d33a63137aa88"
        }'